theme: jekyll-theme-minima
title: Pedro Lacerda's homepage
description: August 2023

show_downloads: false
#["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

# remote_theme: dark-poole
# - pages-themes/primer@v0.2.0
# - pages-themes/tactile@v0.2.0
# - pages-themes/hacker@v0.2.0

plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown

github:
  is_project_page: false # remove view on GitHub button
